---
title: "NIFES data, calculate trends"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
    
---

Based on code from '04_NIVA_data_with_NIFES_3.R' ("H:/Documents/seksjon 212/Indikator 2018/Analyse")  


## 1. Packages + functions  
```{r, message=FALSE, results='hide'}
library(dplyr)
library(tidyr)
library(readxl)
library(ggplot2)
library(mgcv)         # for gam()
library(AICcmodavg)   # for AICc()

source("00_functions.R")
source("16_Trend_functions.R")

```

## 2. Data
```{r}

df_median <- readRDS("Data/11_df_median (2020).rds") %>%
  rename(TISSUE_NAME = Organ) %>%   # avoid a bunch of annoying error messages...
  as.data.frame() 



```

## 3. Function for performing regression    
From '04_NIVA_data_with_NIFES_3.R', but added 'areas' as input ('Uttaksområde')  
```{r}
#
# Get regression for all
#
get_regression_statistics <- function(par, tissue, position){
  df_median_sel <- df_median  %>% 
    filter(Parameter %in% par & Posisjon %in% position & TISSUE_NAME %in% tissue & !is.na(Conc)) %>%
    rename(YEAR = Year, Median = Conc)
  df_med_object <- df_median_sel %>% select_for_regr_a() %>% select_for_regr_b()
  modelresults <- try(calc_models_gam(df_med_object, log = TRUE))
  if (class(modelresults)[[1]] != "try-error"){
    res <- statistics_for_excel(df_med_object, modelresults, gam = TRUE)
  } else {
    res <- statistics_for_excel_empty(df_median_sel)
    res$N <- df_med_object$N
    res$Nplus <- df_med_object$Nplus
  }
  data.frame(Posisjon = position, Parameter = par, TISSUE_NAME = tissue, res, stringsAsFactors = FALSE)
}

get_tissue <- function(par){
  ifelse(par %in% "HG", "Muskel", "Lever")
}

# Test
# get_regression_statistics("HG", "Muskel", c("71,60N 21,30E")) 

```


### Table of areas and years  
```{r}

xtabs(~Year + Posisjon, df_median)
# xtabs(~Organ, df_median)

xtabs(~Year + TISSUE_NAME + Art, df_median)

```

## 4. Regression on 'df_median'  

### Make table for regression  
```{r}
# Doing regression for all
sel_param <- c("CD", "HG", "PB", "HCB", "DDEPP", "CB_S7", "DDEPP", "BDE6S")

timeseries <- df_median %>%
  filter(Parameter %in% sel_param) %>%
  count(Posisjon, Parameter) %>%
  mutate(TISSUE_NAME = get_tissue(Parameter))

timeseries
  
```

### Perform all regressions
```{r}

# Perform all regressions
nifes_regression <- 1:nrow(timeseries) %>% purrr::map_dfr(
  ~get_regression_statistics(
    timeseries$Parameter[.], 
    timeseries$TISSUE_NAME[.], 
    timeseries$Posisjon[.])
  )

# Add 'trend_text'
nifes_regression <- nifes_regression %>%
  mutate(trend_text = case_when(
    N < 5 ~ "Too little data",
    N >= 5 & Nplus < 5 ~ "Too few data above LOQ",
    Model_used %in% c("Linear", "Nonlinear") & Dir_change == "Up" ~ "Trend up",
    Model_used %in% c("Linear", "Nonlinear") & Dir_change == "Down" ~ "Trend down",
    Model_used %in% c("Linear", "Nonlinear") & Dir_change == "" ~ "No trend",
    ))


# Adding trend symbol
# Based on "18_Time_series_write_to_Excel_functions.R"
df_symbol_to_trend <- tibble(
  trend_symbol = c("§", "«", "¢", "é", "ê"),
  trend_text = c("Too little data", "Too few data above LOQ", "No trend", "Trend up", "Trend down"),
  trend = c(0,0,1,2,3)
  )

nifes_regression <- nifes_regression %>%
  left_join(df_symbol_to_trend[,c("trend_text", "trend")]) %>% # adding trend symbol
  rename(PARAM = Parameter)   # To fit with NIVA data


```

### Check
```{r}

nifes_regression %>% select(Posisjon, PARAM, TISSUE_NAME, Nplus, Model_used, Dir_change, trend_text)  # %>% View()

```


## 5. Save
```{r}

overwrite <- FALSE

if (overwrite){
  saveRDS(nifes_regression, "Data/12_nifes_regression (2020).rds")
  write.csv(nifes_regression, "Data/12_nifes_regression (2020).csv", quote = FALSE, row.names = FALSE)
}

```



